from __init__ import *
from app.models.author import Author

def test_author():
    mock_extracted_hash = {u'works_written': {u'count': 3.0, u'valuetype': u'object', u'values': [{u'lang': u'en', u'text': u'Business @ the Speed of Thought: Using a Digital Nervous System', u'id': u'/m/01xfkm', u'timestamp': u'2008-07-13T18:56:21Z', u'creator': u'/user/earlye'}, {u'lang': u'en', u'text': u'The Road Ahead', u'id': u'/m/01sqgw', u'timestamp': u'2008-11-03T17:25:53.001Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Open Letter to Hobbyists', u'id': u'/m/01lt72', u'timestamp': u'2013-12-12T18:13:07Z', u'creator': u'/user/fact_farm'}]}, u'book_editions_published': {u'count': 16.0, u'valuetype': u'object', u'values': [{u'lang': u'en', u'text': u'Los Negocios En La Era Digital', u'id': u'/m/04txs8t', u'timestamp': u'2008-11-10T20:09:47.005Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Der Weg Nach Vorn', u'id': u'/m/04txs91', u'timestamp': u'2008-11-10T20:09:47.006Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'The Road Ahead', u'id': u'/m/04txs98', u'timestamp': u'2008-11-10T20:09:47.007Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Business at the Speed of Thought (Penguin Joint Venture Readers)', u'id': u'/m/04txs9q', u'timestamp': u'2008-11-10T20:09:47.008Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Bill Gates speaks', u'id': u'/m/04txs9z', u'timestamp': u'2008-11-10T20:09:47.009Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Business @ the Speed of Thought', u'id': u'/m/04v22tc', u'timestamp': u'2008-11-11T19:51:15.001Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Business @ the Speed of Thought: Using a Digital Nervous System', u'id': u'/m/04v22vd', u'timestamp': u'2008-11-11T19:51:15.005Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'Business @ the Speed of Thought', u'id': u'/m/04v22vx', u'timestamp': u'2008-11-11T19:51:15.006Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'The Road Ahead', u'id': u'/m/04vhdjk', u'timestamp': u'2008-11-13T02:26:15Z', u'creator': u'/user/ts_bot'}, {u'lang': u'en', u'text': u'The Road Ahead', u'id': u'/m/04vhdk0', u'timestamp': u'2008-11-13T02:26:15.001Z', u'creator': u'/user/ts_bot'}]}, u'openlibrary_id': {u'count': 1.0, u'valuetype': u'string', u'values': [{u'lang': '', u'text': u'OL34537A', u'timestamp': u'2009-05-04T19:38:11Z', u'value': u'OL34537A', u'creator': u'/user/ts_bot'}]}, '/book/author': {}}
    author = Author()
    author.extract(mock_extracted_hash)
    assert_equal(author.books, ['Business @ the Speed of Thought: Using a Digital Nervous System', 'The Road Ahead', 'Open Letter to Hobbyists'])
    assert_equal(author.books_about, ['Los Negocios En La Era Digital', 'Der Weg Nach Vorn', 'The Road Ahead', 'Business at the Speed of Thought (Penguin Joint Venture Readers)', 'Bill Gates speaks', 'Business @ the Speed of Thought', 'Business @ the Speed of Thought: Using a Digital Nervous System'])
